<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/template/images/logodefault.jpg',
            'nama' => 'SekolahanDemo',
            'npsn' => 20100289,
            'alamat' => 'JalanBaros',
            'kodepos' => 10260,
            'desa' => 'Baros',
            'kecamatan' => 'TanahAbang',
            'kota' => 'KotaJakartaPusat',
            'provinsi' => 'Prov.D.K.I.Jakarta',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMP',
            'fax' => '-',
            'telp' => '--',
            'email' => '[emailprotected]',
            'website' => 'http://www.smp1908.blogspot.com',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/MA%20KEJURUAN%20UNGGULAN%20INFORMATIKA.png',
            'nama' => 'MAKEJURUANUNGGULANINFORMATIKA',
            'npsn' => 69975837,
            'alamat' => 'JL.KOSTRADRAYA',
            'kodepos' => 12260,
            'desa' => 'PetukanganUtara',
            'kecamatan' => 'Pesanggrahan',
            'kota' => 'KotaJakartaSelatan',
            'provinsi' => 'Prov.D.K.I.Jakarta',
            'status' => 'SWASTA',
            'waktu' => 'seharipenuh/5hari',
            'jenjang' => 'MAK',
            'fax' => '021-58907647',
            'telp' => '',
            'email' => '[emailprotected],[emailprotected]',
            'website' => 'www.mak-ui.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20DINAMIKA%20PEMBANGUNAN%201%20JAKARTA.png',
            'nama' => 'SMKSDINAMIKAPEMBANGUNAN1JAKARTA',
            'npsn' => 20103703,
            'alamat' => 'JL.RAYAPENGGILINGAN99',
            'kodepos' => 13940,
            'desa' => 'PENGGILINGAN',
            'kecamatan' => 'Cakung',
            'kota' => 'KotaJakartaTimur',
            'provinsi' => 'Prov.D.K.I.Jakarta',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '(021)46820052',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkdp1jkt.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20PARIWISATA%20METLAND%20SCHOOL.png',
            'nama' => 'SMKPARIWISATAMETLANDSCHOOL',
            'npsn' => 69893377,
            'alamat' => 'JL.TAMANMETRORAYAMETLANDTRANSYOGI',
            'kodepos' => 0,
            'desa' => 'Cileungsi',
            'kecamatan' => 'Cileungsi',
            'kota' => 'Bogor',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMP%20NEGERI%201%20GUNUNGPUTRI.jpeg',
            'nama' => 'SMPNEGERI1GUNUNGPUTRI',
            'npsn' => 20200639,
            'alamat' => 'Jl.MelatiNo.34',
            'kodepos' => 16965,
            'desa' => 'WANAHERANG',
            'kecamatan' => 'Gunungputri',
            'kota' => 'Bogor',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMP',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://www.smpn1gp.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20DOA%20BANGSA.jpeg',
            'nama' => 'SMKSDOABANGSA',
            'npsn' => 69726062,
            'alamat' => 'JL.WRSUPRATMANNO.333',
            'kodepos' => 43364,
            'desa' => 'Citepus',
            'kecamatan' => 'PelabuhanRatu',
            'kota' => 'Sukabumi',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0266435454',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkdb.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20YASTI%20CISAAT%20SUKABUMI.jpeg',
            'nama' => 'SMKSYASTICISAATSUKABUMI',
            'npsn' => 20202277,
            'alamat' => 'JL.VETERANNO.66CISAATSUKABUMI',
            'kodepos' => 43152,
            'desa' => 'CISAAT',
            'kecamatan' => 'Cisaat',
            'kota' => 'Sukabumi',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0266228203',
            'email' => '[emailprotected]',
            'website' => 'http://smkyasti.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20NEGERI%202%20CILAKU.jpeg',
            'nama' => 'SMKNEGERI2CILAKU',
            'npsn' => 20203873,
            'alamat' => 'Jln.PerintisKemerdekaanNo.02',
            'kodepos' => 43285,
            'desa' => 'Sirnagalih',
            'kecamatan' => 'Cilaku',
            'kota' => 'Cianjur',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0263264794',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkn2cilakucianjur.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20CENDIKIA%20PASEH.jpeg',
            'nama' => 'SMKCENDIKIAPASEH',
            'npsn' => 69774725,
            'alamat' => 'JL.RAYAMAJALAYA-CICALENGKAKM3KP.BOJONG',
            'kodepos' => 40383,
            'desa' => 'Cigentur',
            'kecamatan' => 'Paseh',
            'kota' => 'Bandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '02285962381',
            'email' => '[emailprotected]',
            'website' => 'http://smkcendikiapaseh.blogspot.com',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20YADIKA%202%20CIJAGRA%20PASEH.png',
            'nama' => 'SMKYADIKA2CIJAGRAPASEH',
            'npsn' => 20256568,
            'alamat' => 'JL.LEGOKMUNCANGDESACIJAGRAKEC.PASEH',
            'kodepos' => 40383,
            'desa' => 'Cijagra',
            'kecamatan' => 'Paseh',
            'kota' => 'Bandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Siang/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://smksyadika2cijagra-sor.sch-id.net',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMA%20PASUNDAN%20RANCAEKEK.png',
            'nama' => 'SMAPASUNDANRANCAEKEK',
            'npsn' => 20227918,
            'alamat' => 'JL.DAHLIARAYABUMIRANCAEKEKKENCANA',
            'kodepos' => 40394,
            'desa' => 'RancaekekKencana',
            'kecamatan' => 'Rancaekek',
            'kota' => 'Bandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMA',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://smapasundanrancaekek.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20ITIKURIH%20HIBARNA%20CIPARAY.png',
            'nama' => 'SMKITIKURIHHIBARNACIPARAY',
            'npsn' => 20256565,
            'alamat' => 'JL.RayaLaswiNO.782Ciparay',
            'kodepos' => 40381,
            'desa' => 'Ciparay',
            'kecamatan' => 'Ciparay',
            'kota' => 'Bandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0225953182',
            'email' => '[emailprotected]',
            'website' => 'http://smkitikurihhibarna.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20PASUNDAN%202%20BANJARAN.png',
            'nama' => 'SMKPASUNDAN2BANJARAN',
            'npsn' => 20206220,
            'alamat' => 'JL.STASIUNTIMURNO.62',
            'kodepos' => 40377,
            'desa' => 'Banjaran',
            'kecamatan' => 'Banjaran',
            'kota' => 'Bandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0225941441',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkpasundan2banjaran.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20YPAI%20RAHAYU.png',
            'nama' => 'SMKYPAIRAHAYU',
            'npsn' => 69812110,
            'alamat' => 'JL.MAHMUDNO.101',
            'kodepos' => 40218,
            'desa' => 'Rahayu',
            'kecamatan' => 'Margaasih',
            'kota' => 'Bandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://smkypairahayu.mysch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20ANGKASA%201%20MARGAHAYU.jpeg',
            'nama' => 'SMKANGKASA1MARGAHAYU',
            'npsn' => 20228515,
            'alamat' => 'JL.HERCULESIVNO.1MARGAHAYU',
            'kodepos' => 40229,
            'desa' => 'Sulaeman',
            'kecamatan' => 'Margahayu',
            'kota' => 'Bandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0225416703',
            'email' => '[emailprotected]',
            'website' => 'http://www.smk-angkasa1.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMAS%20PASUNDAN%20GARUT.jpeg',
            'nama' => 'SMASPASUNDANGARUT',
            'npsn' => 20227447,
            'alamat' => 'JL.PASUNDANNO.68',
            'kodepos' => 44112,
            'desa' => 'Kotakulon',
            'kecamatan' => 'GarutKota',
            'kota' => 'Garut',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMA',
            'fax' => '-',
            'telp' => '02622800837',
            'email' => '[emailprotected]',
            'website' => 'http://smapasgar.blogspot.com',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMP%20PASUNDAN%20LELES.jpeg',
            'nama' => 'SMPPASUNDANLELES',
            'npsn' => 20209263,
            'alamat' => 'JalanRayaLeles-Garut',
            'kodepos' => 44152,
            'desa' => 'Leles',
            'kecamatan' => 'Leles',
            'kota' => 'Garut',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMP',
            'fax' => '-',
            'telp' => '-',
            'email' => '[emailprotected]',
            'website' => 'http://smppasundanleles.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20PERTIWI%20KUNINGAN.png',
            'nama' => 'SMKPERTIWIKUNINGAN',
            'npsn' => 20212908,
            'alamat' => 'JL.SILIWANGI26AKASTURIKUNINGAN',
            'kodepos' => 45521,
            'desa' => 'KRAMATMULYA',
            'kecamatan' => 'Kramatmulya',
            'kota' => 'Kuningan',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '02328893095',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkpertiwikuningan.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20MUHAMMADIYAH%203%20JALAKSANA.png',
            'nama' => 'SMKMUHAMMADIYAH3JALAKSANA',
            'npsn' => 20254698,
            'alamat' => 'Jln.RayaJalaksanaNo.188',
            'kodepos' => 45554,
            'desa' => 'Jalaksana',
            'kecamatan' => 'Jalaksana',
            'kota' => 'Kuningan',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '-',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%201%20GEBANG.jpeg',
            'nama' => 'SMKN1GEBANG',
            'npsn' => 20253778,
            'alamat' => 'JL.RAYAGEBANGILIRPERUMGEBANGPERMAINO.01',
            'kodepos' => 45194,
            'desa' => 'GebangIlir',
            'kecamatan' => 'Gebang',
            'kota' => 'Cirebon',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '02318840267',
            'email' => '[emailprotected]',
            'website' => 'http://smkn1-gebang.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20ULIL%20ALBAB%20DEPOK.jpeg',
            'nama' => 'SMKSULILALBABDEPOK',
            'npsn' => 20214818,
            'alamat' => 'JL.RAYAKEBAREPANNO.6DEPOK-CIREBON',
            'kodepos' => 45653,
            'desa' => 'KasugenganLor',
            'kecamatan' => 'Depok',
            'kota' => 'Cirebon',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0231341508',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkulilalbabdepokcrb.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20PASUNDAN%20SUBANG.png',
            'nama' => 'SMKSPASUNDANSUBANG',
            'npsn' => 20233684,
            'alamat' => 'JL.BAGUSYABIN(KOPTIRAYA)NO.6SUBANG',
            'kodepos' => 41213,
            'desa' => 'Cigadung',
            'kecamatan' => 'Subang',
            'kota' => 'Subang',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '(0260)411778',
            'email' => '[emailprotected]',
            'website' => 'http://smkpasundansubang.sch.id/',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%201%20CIPUNAGARA.jpeg',
            'nama' => 'SMKN1CIPUNAGARA',
            'npsn' => 20233677,
            'alamat' => 'KOMPLEKLAPANGANMERAH',
            'kodepos' => 41257,
            'desa' => 'Tanjung',
            'kecamatan' => 'Cipunagara',
            'kota' => 'Subang',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://smkn1cipunagara.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20IT%20RAUDHATUL%20ULUUM.jpeg',
            'nama' => 'SMKSITRAUDHATULULUUM',
            'npsn' => 69774751,
            'alamat' => 'KP.CIJEREHILIRRT11/03DSTENJOLAYA',
            'kodepos' => 41283,
            'desa' => 'Tenjolaya',
            'kecamatan' => 'Kasomalang',
            'kota' => 'Subang',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://yarus.co.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20INFORMATIKA%20PASUNDAN%20PURWAKARTA.jpeg',
            'nama' => 'SMKSINFORMATIKAPASUNDANPURWAKARTA',
            'npsn' => 20268713,
            'alamat' => 'JL.R.E.MARTADINATA,NO.111',
            'kodepos' => 41111,
            'desa' => 'Nagrikidul',
            'kecamatan' => 'Purwakarta',
            'kota' => 'Purwakarta',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '-',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20TEKNOLOGI.png',
            'nama' => 'SMKTEKNOLOGI',
            'npsn' => 69947173,
            'alamat' => 'DusunKarangmulyaRT008RW004',
            'kodepos' => 41371,
            'desa' => 'Lemahmulya',
            'kecamatan' => 'Majalaya',
            'kota' => 'Karawang',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0267',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20TRI%20MITRA%20KARAWANG.jpeg',
            'nama' => 'SMKSTRIMITRAKARAWANG',
            'npsn' => 20237434,
            'alamat' => 'Jl.ByPassJomin-JominBarat',
            'kodepos' => 41373,
            'desa' => 'JominBarat',
            'kecamatan' => 'Kotabaru',
            'kota' => 'Karawang',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '02648385140',
            'email' => '[emailprotected]',
            'website' => 'http://smktrimitra.tmkm.ac.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20AL%20FATHIMIYAH.png',
            'nama' => 'SMKSALFATHIMIYAH',
            'npsn' => 20258509,
            'alamat' => 'JL.PERUMPERURINO.69TELUKJAMBETIMURKARAWANG',
            'kodepos' => 41361,
            'desa' => 'Pinayungan',
            'kecamatan' => 'TelukJambeTimur',
            'kota' => 'Karawang',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://www.alfathimiyah.com',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20TUNAS%20BANGSA%20NGAMPRAH.jpeg',
            'nama' => 'SMKSTUNASBANGSANGAMPRAH',
            'npsn' => 20228557,
            'alamat' => 'JLHGOFURNO.162',
            'kodepos' => 40552,
            'desa' => 'Tanimulya',
            'kecamatan' => 'Ngamprah',
            'kota' => 'BandungBarat',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0226623319',
            'email' => '[emailprotected]',
            'website' => 'http://www.smktunasbangsangamprah.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMP%20PASUNDAN%209.png',
            'nama' => 'SMPPASUNDAN9',
            'npsn' => 20219496,
            'alamat' => 'Jl.BabakanCiparay',
            'kodepos' => 40221,
            'desa' => 'Sukahaji',
            'kecamatan' => 'BabakanCiparay',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMP',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://www.smppasundan9bdg.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20TERPADU%20AD%20DIMYATI.png',
            'nama' => 'SMKSTERPADUADDIMYATI',
            'npsn' => 20271622,
            'alamat' => 'JL.KH.WAHIDHASYIM(KOPO)NO.433',
            'kodepos' => 40235,
            'desa' => 'KebonLega',
            'kecamatan' => 'BojongLoaKidul',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '022-5432379',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkterpaduaddimyati.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMAS%20PASUNDAN%201%20BANDUNG.x-empty',
            'nama' => 'SMASPASUNDAN1BANDUNG',
            'npsn' => 20219767,
            'alamat' => 'Jl.BalonggedeNo.28',
            'kodepos' => 40251,
            'desa' => 'BalongGede',
            'kecamatan' => 'Regol',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMA',
            'fax' => '-',
            'telp' => '4210443',
            'email' => '[emailprotected]',
            'website' => 'http://www.smapasundan1-bandung.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20PASUNDAN%201%20BANDUNG.jpeg',
            'nama' => 'SMKSPASUNDAN1BANDUNG',
            'npsn' => 20219137,
            'alamat' => 'JLBALONGGEDENO.44BANDUNG',
            'kodepos' => 40251,
            'desa' => 'BalongGede',
            'kecamatan' => 'Regol',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0224241147',
            'email' => '[emailprotected]',
            'website' => 'http://smkpasundan1bdg.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20BINA%20WARGA%20BANDUNG.png',
            'nama' => 'SMKSBINAWARGABANDUNG',
            'npsn' => 20219289,
            'alamat' => 'JL.BUAHBATUNO.135BANDUNG',
            'kodepos' => 40264,
            'desa' => 'Turangga',
            'kecamatan' => 'Lengkong',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '7305120',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMAS%20KARTIKA%20XIX-3.png',
            'nama' => 'SMASKARTIKAXIX-3',
            'npsn' => 20219726,
            'alamat' => 'JL.ACEHNO.108',
            'kodepos' => 40113,
            'desa' => 'Merdeka',
            'kecamatan' => 'SumurBandung',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMA',
            'fax' => '-',
            'telp' => '-',
            'email' => '[emailprotected]',
            'website' => 'http://smakartikasiliwangi3.co.cc',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%201%20BANDUNG.webp',
            'nama' => 'SMKN1BANDUNG',
            'npsn' => 20219178,
            'alamat' => 'JL.WASTUKANCANANO.3',
            'kodepos' => 40117,
            'desa' => 'BabakanCiamis',
            'kecamatan' => 'SumurBandung',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '022.4209105',
            'email' => '[emailprotected]',
            'website' => 'http://www.smknegeri1bandung.com',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20PASUNDAN%203%20BANDUNG.jpeg',
            'nama' => 'SMKSPASUNDAN3BANDUNG',
            'npsn' => 20219158,
            'alamat' => 'JL.SUMATERANO.41',
            'kodepos' => 40117,
            'desa' => 'BabakanCiamis',
            'kecamatan' => 'SumurBandung',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0224202881',
            'email' => '[emailprotected]',
            'website' => 'http://smkpasundan3bandung.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMAS%20PASUNDAN%203%20BANDUNG.png',
            'nama' => 'SMASPASUNDAN3BANDUNG',
            'npsn' => 20219765,
            'alamat' => 'JL.KEBONJATINO.31',
            'kodepos' => 40181,
            'desa' => 'KEBONJERUK',
            'kecamatan' => 'Andir',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMA',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://smapasundan3bandung.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20PASUNDAN%202%20BANDUNG.png',
            'nama' => 'SMKSPASUNDAN2BANDUNG',
            'npsn' => 20219148,
            'alamat' => 'PELITAKARYA1NO.2',
            'kodepos' => 40184,
            'desa' => 'MALEBER',
            'kecamatan' => 'Andir',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '022/6034059',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkpasundan2bdg.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/merdeka-bdg.png',
            'nama' => 'SMKSMERDEKABANDUNG',
            'npsn' => 20219162,
            'alamat' => 'JLPAHLAWANNO.54BANDUNG',
            'kodepos' => 40124,
            'desa' => 'Neglasari',
            'kecamatan' => 'CibeunyingKaler',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0227216143',
            'email' => '[emailprotected]',
            'website' => 'http://smkmerdekabdg.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20BAKTI%20BANGSA.jpeg',
            'nama' => 'SMKSBAKTIBANGSA',
            'npsn' => 20275333,
            'alamat' => 'SARIJADIBLOKI',
            'kodepos' => 40151,
            'desa' => 'Sarijadi',
            'kecamatan' => 'Sukasari',
            'kota' => 'KotaBandung',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '02282003377',
            'email' => '[emailprotected]',
            'website' => 'http://smkbaktibangsabdg.mysch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20VETERAN%20CIREBON.png',
            'nama' => 'SMKSVETERANCIREBON',
            'npsn' => 20222164,
            'alamat' => 'PEMUDANO.33',
            'kodepos' => 45132,
            'desa' => 'SUNYARAGI',
            'kecamatan' => 'Kesambi',
            'kota' => 'KotaCirebon',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0231/235930',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkveterancirebon.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20TUNAS%20MEDIA.png',
            'nama' => 'SMKTUNASMEDIA',
            'npsn' => 69849364,
            'alamat' => 'JL.RAYACINANGKA88',
            'kodepos' => 16516,
            'desa' => 'Kedaung',
            'kecamatan' => 'Sawangan',
            'kota' => 'KotaDepok',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0217440713',
            'email' => '[emailprotected]',
            'website' => 'http://www.smktunasmedia.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20Taruna%20Bhakti.jpeg',
            'nama' => 'SMKTarunaBhakti',
            'npsn' => 20229232,
            'alamat' => 'JalanpekapuranRT02/07CurugCimanggiskotadepok',
            'kodepos' => 16953,
            'desa' => 'Curug',
            'kecamatan' => 'Cimanggis',
            'kota' => 'KotaDepok',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0218744810',
            'email' => '[emailprotected]',
            'website' => 'http://www.smktarunabhakti.net',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20CAKRA%20NUSANTARA,%20KOTA%20DEPOK.png',
            'nama' => 'SMKCAKRANUSANTARA,KOTADEPOK',
            'npsn' => 20271540,
            'alamat' => 'JL.UJUNGSELATANPERUMWISMACAKRART04/09LIMODEPOK',
            'kodepos' => 16515,
            'desa' => 'LIMO',
            'kecamatan' => 'Limo',
            'kota' => 'KotaDepok',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://www.smk.charnoestcyber.com',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/MA%20NEGERI%20CIMAHI.png',
            'nama' => 'MANEGERICIMAHI',
            'npsn' => 20277137,
            'alamat' => 'JL.KIHAPITBARATNO.319LEUWIGAJAH',
            'kodepos' => 0,
            'desa' => 'Leuwigajah',
            'kecamatan' => 'CimahiSelatan',
            'kota' => 'KotaCimahi',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'NEGERI',
            'waktu' => '',
            'jenjang' => 'MA',
            'fax' => '-',
            'telp' => '',
            'email' => '',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20PASUNDAN%203.png',
            'nama' => 'SMKPASUNDAN3',
            'npsn' => 20268626,
            'alamat' => 'JL.MELONGRAYANO.2PERUMCIJERAHII',
            'kodepos' => 40534,
            'desa' => 'Melong',
            'kecamatan' => 'CimahiSelatan',
            'kota' => 'KotaCimahi',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkpasundan3cimahi.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMA%20PASUNDAN%201.png',
            'nama' => 'SMAPASUNDAN1CIMAHI',
            'npsn' => 20224106,
            'alamat' => 'JL.TERUSANNO.32',
            'kodepos' => 40525,
            'desa' => 'Cimahi',
            'kecamatan' => 'CimahiTengah',
            'kota' => 'KotaCimahi',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMA',
            'fax' => '0226654449',
            'telp' => '-',
            'email' => '[emailprotected]',
            'website' => 'http://www.smapasundan1cimahi.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20PASUNDAN%201.png',
            'nama' => 'SMKPASUNDAN1',
            'npsn' => 20224133,
            'alamat' => 'JL.ENCEPKARTAWIRIANO.97A',
            'kodepos' => 40512,
            'desa' => 'Citeureup',
            'kecamatan' => 'CimahiUtara',
            'kota' => 'KotaCimahi',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20MJPS%203%20TASIKMALAYA.png',
            'nama' => 'SMKSMJPS3TASIKMALAYA',
            'npsn' => 20224517,
            'alamat' => 'Jl.CiwaasTamansariPOBox258Gobras',
            'kodepos' => 46196,
            'desa' => 'Sukahurip',
            'kecamatan' => 'Tamansari',
            'kota' => 'KotaTasikmalaya',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0265-323954',
            'email' => '[emailprotected]',
            'website' => 'http://smkmjps3tsm.mysch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%201%20BUKATEJA.png',
            'nama' => 'SMKN1BUKATEJA',
            'npsn' => 20303106,
            'alamat' => 'JL.RAYAPURWANDARU-BUKATEJA',
            'kodepos' => 53382,
            'desa' => 'BUKATEJA',
            'kecamatan' => 'Bukateja',
            'kota' => 'Purbalingga',
            'provinsi' => 'Prov.JawaTengah',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0286-476110',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkn1bukateja.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%20KECIL%20KEJOBONG.png',
            'nama' => 'SMKNKECILKEJOBONG',
            'npsn' => 20356184,
            'alamat' => 'RAYASAMBONG',
            'kodepos' => 53392,
            'desa' => 'Timbang',
            'kecamatan' => 'Kejobong',
            'kota' => 'Purbalingga',
            'provinsi' => 'Prov.JawaTengah',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://www.smknkejobong.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/ykvxw.jpg',
            'nama' => 'SMKSNUMAARIFKUDUS',
            'npsn' => 20317578,
            'alamat' => 'DSPRAMBATANLOR679',
            'kodepos' => 59361,
            'desa' => 'PRAMBATANLOR',
            'kecamatan' => 'Kaliwungu',
            'kota' => 'Kudus',
            'provinsi' => 'Prov.JawaTengah',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0291/4244370',
            'email' => '[emailprotected]',
            'website' => 'http://www.smk-maarifkudus.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20PGRI%2001%20SUKOREJO.png',
            'nama' => 'SMKSPGRI01SUKOREJO',
            'npsn' => 20351652,
            'alamat' => 'JL.SAPENNO.49SUKOREJOKENDAL',
            'kodepos' => 51363,
            'desa' => 'Sukorejo',
            'kecamatan' => 'Sukorejo',
            'kota' => 'Kendal',
            'provinsi' => 'Prov.JawaTengah',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '(0294)451330',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkpgri01sukorejo.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/muhammadiyah-bligo.png',
            'nama' => 'SMKMUHAMMADIYAHBLIGO',
            'npsn' => 20323506,
            'alamat' => 'SapugarutGg.7Buaran',
            'kodepos' => 51171,
            'desa' => 'Bligo',
            'kecamatan' => 'Buaran',
            'kota' => 'Pekalongan',
            'provinsi' => 'Prov.JawaTengah',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '(0285)4415132',
            'email' => '[emailprotected]',
            'website' => 'http://smkmuhbligo.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20MUHAMMADIYAH%201%20PEMALANG.png',
            'nama' => 'SMKSMUHAMMADIYAH1PEMALANG',
            'npsn' => 20324225,
            'alamat' => 'JL.DR.CIPTOMANGUNKUSUMO8PEMALANG',
            'kodepos' => 52319,
            'desa' => 'Bojongbata',
            'kecamatan' => 'Pemalang',
            'kota' => 'Pemalang',
            'provinsi' => 'Prov.JawaTengah',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0284-322177',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20PLUS%20DARUSSALAM%20BANGSALSARI.jpeg',
            'nama' => 'SMKSPLUSDARUSSALAMBANGSALSARI',
            'npsn' => 20564466,
            'alamat' => 'JL.PROYEKUPCATISNOGAMBAR',
            'kodepos' => 68154,
            'desa' => 'Tisnogambar',
            'kecamatan' => 'Bangsalsari',
            'kota' => 'Jember',
            'provinsi' => 'Prov.JawaTimur',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://smkplusdarussalambss.sch.id/',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20MUHAMMADIYAH%206%20ROGOJAMPI.png',
            'nama' => 'SMKSMUHAMMADIYAH6ROGOJAMPI',
            'npsn' => 20525624,
            'alamat' => 'JL.KH.HASYIMASYARINO.38',
            'kodepos' => 68462,
            'desa' => 'ROGOJAMPI',
            'kecamatan' => 'Rogojampi',
            'kota' => 'Banyuwangi',
            'provinsi' => 'Prov.JawaTimur',
            'status' => 'SWASTA',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0333631793',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkmuh6rgj.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20MUH%208%20SILIRAGUNG.png',
            'nama' => 'SMKSMUH8SILIRAGUNG',
            'npsn' => 20525626,
            'alamat' => 'JL.MT.HARIONONO.42',
            'kodepos' => 68488,
            'desa' => 'Siliragung',
            'kecamatan' => 'Siliragung',
            'kota' => 'Banyuwangi',
            'provinsi' => 'Prov.JawaTimur',
            'status' => 'SWASTA',
            'waktu' => 'Siang/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '(0333)713797',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkmodel8.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20NURUS%20SHOBAH.jpeg',
            'nama' => 'SMKNURUSSHOBAH',
            'npsn' => 69958434,
            'alamat' => 'DESAMANTAJUN',
            'kodepos' => 69454,
            'desa' => 'Mantajun',
            'kecamatan' => 'Dasuk',
            'kota' => 'Sumenep',
            'provinsi' => 'Prov.JawaTimur',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20SWASTA%20YAPIM%20SIAK%20HULU.x-empty',
            'nama' => 'SMKSWASTAYAPIMSIAKHULU',
            'npsn' => 10496613,
            'alamat' => 'KOMPLEKGRIYAASRIPASIRPUTIH',
            'kodepos' => 28452,
            'desa' => 'DesaBaru',
            'kecamatan' => 'SiakHulu',
            'kota' => 'Kampar',
            'provinsi' => 'Prov.Riau',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '076173091',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20SWASTA%20BAKTI%20AGRO%20MANDIRI.png',
            'nama' => 'SMKSWASTABAKTIAGROMANDIRI',
            'npsn' => 69939602,
            'alamat' => 'KPPSimpangKananKM14,5',
            'kodepos' => 29255,
            'desa' => 'TanjungSimpang',
            'kecamatan' => 'Pelangiran',
            'kota' => 'IndragiriHilir',
            'provinsi' => 'Prov.Riau',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20MUHAMMADIYAH%203%20METRO.jpeg',
            'nama' => 'SMKSMUHAMMADIYAH3METRO',
            'npsn' => 10807611,
            'alamat' => 'JL.SOEKARNO-HATTA',
            'kodepos' => 34125,
            'desa' => 'MULYOJATI',
            'kecamatan' => 'MetroBarat',
            'kota' => 'KotaMetro',
            'provinsi' => 'Prov.Lampung',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '072547733',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkmuh3metro.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%202%20BANJARMASIN.jpeg',
            'nama' => 'SMKN2BANJARMASIN',
            'npsn' => 30304268,
            'alamat' => 'BRIGJENH.HASANBASRINO.6',
            'kodepos' => 70123,
            'desa' => 'SungaiMiai',
            'kecamatan' => 'BanjarmasinUtara',
            'kota' => 'KotaBanjarmasin',
            'provinsi' => 'Prov.KalimantanSelatan',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '05113304677',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkn2-bjm.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20YADIKA%20MANADO.png',
            'nama' => 'SMKSYADIKAMANADO',
            'npsn' => 40105008,
            'alamat' => 'Jln.RayaMapanget',
            'kodepos' => 95373,
            'desa' => 'Talawaan',
            'kecamatan' => 'Talawaan',
            'kota' => 'MinahasaUtara',
            'provinsi' => 'Prov.SulawesiUtara',
            'status' => 'SWASTA',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '813392',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkyadikamanado.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%202%20LUWUK.png',
            'nama' => 'SMKN2LUWUK',
            'npsn' => 40201635,
            'alamat' => 'JL.LemuruN0.118',
            'kodepos' => 94716,
            'desa' => 'Luwuk',
            'kecamatan' => 'Luwuk',
            'kota' => 'Banggai',
            'provinsi' => 'Prov.SulawesiTengah',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0461-21245,3128032',
            'email' => '[emailprotected]',
            'website' => 'http://smkn2luwuk.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMK%20NEGERI%20BALI%20MANDARA.jpeg',
            'nama' => 'SMKNEGERIBALIMANDARA',
            'npsn' => 69899478,
            'alamat' => 'Jl.AirSanih,DesaKubutambahan',
            'kodepos' => 81172,
            'desa' => 'Kubutambahan',
            'kecamatan' => 'Kubutambahan',
            'kota' => 'Buleleng',
            'provinsi' => 'Prov.Bali',
            'status' => 'NEGERI',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://smknbalimandara.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%202%20SUMBAWA%20BESAR.png',
            'nama' => 'SMKN2SUMBAWABESAR',
            'npsn' => 50203319,
            'alamat' => 'Jl.LingkarSelatanKM04Sumbawa',
            'kodepos' => 84316,
            'desa' => 'Pungka',
            'kecamatan' => 'UnterIwes',
            'kota' => 'Sumbawa',
            'provinsi' => 'Prov.NusaTenggaraBarat',
            'status' => 'NEGERI',
            'waktu' => 'DoubleShift/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '03712620556',
            'email' => '[emailprotected]',
            'website' => 'http://smkn2sumbawabesar.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%205%20REJANG%20LEBONG.png',
            'nama' => 'SMKN5REJANGLEBONG',
            'npsn' => 10702881,
            'alamat' => 'JL.RAYAPU.TANDING',
            'kodepos' => 39182,
            'desa' => 'PasarPadangUlakTanding',
            'kecamatan' => 'PadangUlangTanding',
            'kota' => 'RejangLebong',
            'provinsi' => 'Prov.Bengkulu',
            'status' => 'NEGERI',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%203%20PANDEGLANG.jpeg',
            'nama' => 'SMKN3PANDEGLANG',
            'npsn' => 20600571,
            'alamat' => 'JL.PERINTISKEMERDEKAANCARINGIN-LABUAN',
            'kodepos' => 42264,
            'desa' => 'Caringin',
            'kecamatan' => 'Labuan',
            'kota' => 'Pandeglang',
            'provinsi' => 'Prov.Banten',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '0253804262',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkn3pandeglang.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/pp89p.png',
            'nama' => 'SMKSMODELINKMUBARAKAHKABUPATENSORONG',
            'npsn' => 60403365,
            'alamat' => 'JL.KATAPOPKM.34SP.3MAYAMUKKAB.SORONG',
            'kodepos' => 98451,
            'desa' => 'Makbusun',
            'kecamatan' => 'Mayamuk',
            'kota' => 'Sorong',
            'provinsi' => 'Prov.PapuaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkmodellinksorong.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMP%20NEGERI%2026%20KABUPATEN%20SORONG.png',
            'nama' => 'PPDBDINASPENDIDIKANDANKEBUDAYAANKABUPATENSORONG',
            'npsn' => 69950711,
            'alamat' => 'JL.BOLHOK',
            'kodepos' => 0,
            'desa' => 'KLABINAIN',
            'kecamatan' => 'Aimas',
            'kota' => 'Sorong',
            'provinsi' => 'Prov.PapuaBarat',
            'status' => 'NEGERI',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMP',
            'fax' => '-',
            'telp' => '',
            'email' => '[emailprotected]',
            'website' => '',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%20CIPATUJAH.jpeg',
            'nama' => 'SMKNCIPATUJAH',
            'npsn' => 20269714,
            'alamat' => 'JALANRAYACIPATUJAH',
            'kodepos' => 46189,
            'desa' => 'Darawati',
            'kecamatan' => 'Cipatujah',
            'kota' => 'Tasikmalaya',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '',
            'telp' => '0',
            'email' => '[emailprotected]',
            'website' => 'http://www.smknegericipatujah.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKN%20MANONJAYA.x-empty',
            'nama' => 'SMKNMANONJAYA',
            'npsn' => 20244754,
            'alamat' => 'GUNUNGTANJUNGKM.2,5',
            'kodepos' => 46197,
            'desa' => 'Margahayu',
            'kecamatan' => 'Manonjaya',
            'kota' => 'Tasikmalaya',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'NEGERI',
            'waktu' => 'SehariPenuh/5hari',
            'jenjang' => 'SMK',
            'fax' => '',
            'telp' => '(0265)381767',
            'email' => '[emailprotected]',
            'website' => 'http://www.smknmanonjaya.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20ISLAMIYAH%20CIAWI%20TASIKMALAYA.jpeg',
            'nama' => 'SMKSISLAMIYAHCIAWITASIKMALAYA',
            'npsn' => 20210716,
            'alamat' => 'JL.PESANTRENSRAHTARJUNINGRAHYUKIARAKUDAPAKEMITANCIAWITASIKMALAYA',
            'kodepos' => 46156,
            'desa' => 'Pakemitan',
            'kecamatan' => 'Ciawi',
            'kota' => 'Tasikmalaya',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Siang/6hari',
            'jenjang' => 'SMK',
            'fax' => '',
            'telp' => '(0265)453174',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkislmiyahciawi.sch.id',
            'operator' => 1,
        ]);
        DB::table('sekolah')->insert([
            'gambar' => 'https://sekolahpedia.id/medias/logosekolah/SMKS%20PLUS%20AL%20HASANAH.png',
            'nama' => 'SMKSPLUSALHASANAH',
            'npsn' => 20268067,
            'alamat' => 'JL.RAYAGUNUNGTANJUNGKM.8',
            'kodepos' => 46197,
            'desa' => 'Cinunjang',
            'kecamatan' => 'Gunungtanjung',
            'kota' => 'Tasikmalaya',
            'provinsi' => 'Prov.JawaBarat',
            'status' => 'SWASTA',
            'waktu' => 'Pagi/6hari',
            'jenjang' => 'SMK',
            'fax' => '',
            'telp' => '0265/2390146',
            'email' => '[emailprotected]',
            'website' => 'http://www.smkplus-alhasanah.sch.id',
            'operator' => 1,
        ]);
    }
}
